DROP TABLE IF EXISTS dbo.t_SIMPSON;
GO

CREATE TABLE dbo.t_SIMPSON
(FNAME  VARCHAR(50) NOT NULL,
JOB_TITLE VARCHAR(60) NOT NULL
							
CONSTRAINT FNAME PRIMARY KEY CLUSTERED(FNAME ASC)
);
GO